# Google Cloud Build Configuration
# 
# This file defines the steps and configurations for a Google Cloud Build process
# that executes a custom script to import data into a Cloud SQL database. 
# The configuration ensures the build process is secure, logging is directed to 
# Cloud Logging, and the operation is executed in a specified worker pool.

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |                       
        # Make the script executable
        chmod +x ./import_data.sh

        # Run the import_data.sh script with the required arguments
        ./import_data.sh \
          "${_IMPORT_DATABASE_INSTANCE_NAME}" \
          "${_IMPORT_DATABASE_INSTANCE_PROJECT}" \
          "${_IMPORT_DATABASE_INSTANCE_REGION}" \
          "tc-tekstack-kps-temp-data-import" \ # GCS bucket for temporary data storage during import
          "${_IMPORT_DATABASE_NAME}" \
          "${_IMPORT_USERNAME}"
        
    secretEnv: ['DATABASE_PASS'] # The database password is injected into the environment from Secret Manager.
    dir: 'sql_server_cloud_build_import/'

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
      name: 'projects/your-project/locations/your-region/workerPools/your-worker-pool' # Specify the worker pool to use for this build.
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_PASSWORD_KEY}/versions/latest
      env: DATABASE_PASS